version: "3.9"

services:
  database_restaurant:
    image: postgres
    container_name: database_restaurant
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=restaurant
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: restaurant
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_restaurant
    depends_on: 
      - database_restaurant

volumes:
  pgdata:
    driver: local